### ISSUE TITLE
Having trouble importing

### ISSUE THREAD

**Issue by jglidden** [posterior/treecat#28]
Hi! I am following the guide in the readme but I'm having trouble at the import step. When I run `treecat import-data data.csv types.csv values.csv '' dataset.pkz` I get an error `TypeError: load_data() takes from 2 to 3 positional arguments but 4 were given`. It looks like from the code maybe the function is expecting a list of dataset csvs rather than just one file?

**Comment by fritzo** [comment]
Thanks for reporting! I've fixed and added a regression test in ec99fdbf
